const projects = [
  // ── Google Cybersecurity Certificate projects ─────────────────
  {
    title: "Investigation Of Suspicious Login Activity Using SQL",
    desc: "I investigated suspicious login activity and scoped device update lists using SQL filters across two internal database tables. Identified 19 after-hours failed logins and 144 anomalous geographic access attempts.",
    tags: ["SQL", "Log Analysis", "Anomaly Detection"],
    link: "./projects/Google-CyberSecurity/InvestigationOfSuspiciousLoginActivityUsingSQL.html",
    done: true,
    category: "google",
  },
  {
    title: "Alert Ticket",
    desc: "I analyzed a phishing email, identified multiple red flags, including a suspicious executable attachment and spoofed sender domain, and confirmed the malicious intent by verifying the SHA-256 file hash against 50+ VirusTotal vendor flags.",
    tags: ["VirusTotal", "Phishing", "Alert Triage", "SHA-256"],
    link: "./projects/Google-CyberSecurity/AlertTicket.html",
    done: true,
    category: "google",
  },
  {
    title: "Security Incident Report",
    desc: "I investigated a multi-stage attack on yummyrecipesforme.com where a former employee exploited a default password via brute force to access the admin panel, injected malicious JavaScript redirecting visitors to a malware site, and documented a full DNS/HTTP attack timeline with remediation recommendations including MFA and account lockout policies.",
    tags: ["Brute Force", "Incident Report","Remediation"],
    link: "./projects/Google-CyberSecurity/SecurityIncidentReport.html",
    done: true,
    category: "google",
  },
  {
    title: "Incident Report Network Traffic Analysis",
    desc: "I documented a DNS and ICMP traffic analysis investigating website accessibility failures, interpreted UDP port 53 unreachable errors, and then I identified potential root causes, including firewall misconfiguration and check the system for signs of an attack.",
    tags: ["Network Traffic Analysis", "DNS", "ICMP", "UDP", "Firewall"],
    link: "./projects/Google-CyberSecurity/IncidentReportNetworkTrafficAnalysis.html",
    done: true,
    category: "google",
  },
  {
    title: "Vulnerability Assessment Report",
    desc: "In this project! I conducted a vulnerability assessment for a publicly accessible MySQL database server using NIST SP 800-30 Rev. 1, I identified threat sources Including competitor, cybercriminal, and insider categories. Then I applied likelihood and severity scoring, and recommended controls including MFA, RBAC, TLS encryption, and IP allowlisting.",
    tags: ["NIST SP 800-30", "Vulnerability Assessment", "Risk Scoring", "Threat Analysis", "Database Security", "RBAC", "MFA"],
    link: "./projects/Google-CyberSecurity/VulnerabilityAssessmentReport.html",
    done: true,
    category: "google",
  },
  {
    title: "PASTA Worksheet",
    desc: "I applied the PASTA threat modeling framework for a sneaker marketplace application, I mapped business and security objectives. I mentioned brute force and SQL injection as primary attack vectors, mentioned how if benefit attackers. and recommended controls including MFA, input sanitization, and encryption to mitigate risk.",
    tags: ["PASTA", "Prepared Statements", "Threat Modeling", "SQL Injection", "Brute Force", "SQL Injection", "Input Sanitization", "Attack Vector"],
    link: "./projects/Google-CyberSecurity/PASTA-Worksheet.html",
    done: true,
    category: "google",
  },
  {
    title: "Cybersecurity Incident Report",
    desc: "I investigated a SYN flood DDoS attack targeting a web server, and recommended both immediate firewall containment and long-term rate-limiting controls.",
    tags: ["DDoS", "SYN Flood", "Packet Analysis", "Rate Limiting", "Firewall", "Traffic Analysis"],
    link: "./projects/Google-CyberSecurity/CybersecurityIncidentReport.html",
    done: true,
    category: "google",
  },
  {
    title: "Access Control Worksheet",
    desc: "Investigated unauthorized system access by a former employee who retained admin-level permissions and active credentials post-termination, violating the Principle of Least Privilege (PoLP). I recommended implementing the AAA framework, MFA, role-based access controls, and automated account deactivation to remediate access control gaps.",
    tags: ["AAA", "MFA", "Access Control","RBAC"],
    link: "./projects/Google-CyberSecurity/AccessControlWorksheet.html",
    done: true,
    category: "google",
  },
  {
    title: "Incident Report Analysis",
    desc: "I documented an ICMP flood DDoS attack applying NIST CSF functions: Identify, Protect, Detect, Respond, and Recover. I traced the root cause to an unconfigured firewall and recommended controls, including ICMP rate limiting, source IP verification, and IDS/IPS deployment to prevent recurrence.",
    tags: ["NIST CSF", "DDoS", "ICMP Flood", "Firewall", "IDS/IPS", "Rate Limiting"],
    link: "./projects/Google-CyberSecurity/IncidentReportAnalysis.html",
    done: true,
    category: "google",
  },
  {
    title: "Risk Register",
    desc: "I conducted a risk assessment for a coastal bank, identifying five operational and cybersecurity risks across funds, customer data, and physical assets, ranked by likelihood and severity using a Risk Matrix to prioritize threats including financial records exposure, business email compromise, and supply chain disruption.",
    tags: ["Risk Assessment", "Risk Matrix", "Likelihood & Severity Scoring","Business Email Compromise", "Banking Security"],
    link: "./projects/Google-CyberSecurity/RiskRegister.html",
    done: true,
    category: "google",
  },
  {
    title: "Security Hardening Recommendations Report",
    desc: "I suggested key hardening controls including Password Policy enforcement, Firewall Configuration, and MFA with technical justification for each. Covers threat mitigation against brute force, DoS/DDoS, and credential compromise, alongside additional measures including patch management, least-privilege access, and secure hardware disposal.",
    tags: ["Security Hardening", "Password Policy", "Firewall", "MFA"],
    link: "./projects/Google-CyberSecurity/SecurityHardeningRecommendationsReport.html",
    done: true,
    category: "google",
  },
  {
    title: "Controls and Compliance Checklist",
    desc: "Conducted a simulated security audit for Botium Toys, evaluating controls across PCI DSS, GDPR, and SOC type 1/2 compliance frameworks, identifying critical security gaps including missing least privilege controls, absent disaster recovery plans, and lack of encryption, and recommending prioritized remediation measures to strengthen the organization's security posture.",
    tags: ["PCI DSS", "GDPR", "SOC Type 1", "SOC Type 2", "Security Audit", "Compliance"],
    link: "./projects/Google-CyberSecurity/ControlsAndComplianceChecklist.html",
    done: true,
    category: "google",
  },
  {
    title: "Data Leak Worksheet",
    desc: "Investigated an insider data leak caused by excessive folder access permissions and failure to revoke access post-meeting, identified violations of the Principle of Least Privilege per NIST SP 800-53 AC-6, and recommended automated access expiration, role-based folder permissions, and regular access audits to prevent recurrence.",
    tags: ["NIST SP 800-53", "PoLP", "Data Leak", "Data Protection", "Role-Based Permissions"],
    link: "./projects/Google-CyberSecurity/DataLeakWorksheet.html",
    done: true,
    category: "google",
  },
  {
    title: "Incident Handler's Journal",
    desc: "Documented a ransomware attack on a healthcare clinic using the 5 W's framework, identifying the threat actor, attack vector, and financial motivation, and raised critical investigative questions regarding ransom payment decisions, regulatory reporting obligations, and future phishing prevention measures.",
    tags: ["Ransomware", "Incident Handler Journal", "5 W's", "HIPAA", "Phishing", "Regulatory Compliance"],
    link: "./projects/Google-CyberSecurity/IncidentHandler'sJournal.html",
    done: true,
    category: "google",
  },


  // ── Independent / Home Lab projects ──────────────────────────────────────────────
  {
    title: "Home SOC Lab",
    desc: "Full-cycle attack simulation and detection using Wazuh SIEM in a home lab environment. Covers everything from infrastructure setup to incident response across 5 parts.",
    tags: ["Wazuh", "SIEM", "Kali Linux", "Brute Force", "Incident Response", "Home Lab"],
    link: "./projects/HOME-LAB/soc-lab-overview.html",
    done: true,
    category: "Home-Lab",
    // subparts are rendered as an expandable list inside this card
    subparts: [
      {
        label: "Overview",
        title: "SOC Lab Overview",
        desc: "Full-cycle attack simulation and detection using Wazuh SIEM in a home lab environment.",
        link: "./projects/HOME-LAB/soc-lab-overview.html",
        done: true,
      },
      {
        label: "Part 1",
        title: "Building the Lab",
        desc: "Deploying Wazuh indexer, server, and dashboard with agent enrollment on a Debian endpoint.",
        link: "./projects/HOME-LAB/part1.html",
        done: true,
      },
      {
        label: "Part 2",
        title: "Attack Simulations",
        desc: "Nmap scanning, Hydra credential brute force, SSH access, and SCP data exfiltration.",
        link: "./projects/HOME-LAB/part2.html",
        done: true,
      },
      {
        label: "Part 3",
        title: "Detection & Analysis",
        desc: "Analyzing 500+ alerts, correlating brute force events, and investigating post-exploitation activity.",
        link: "./projects/HOME-LAB/part3.html",
        done: true,
      },
      {
        label: "Part 4",
        title: "Incident Response",
        desc: "Alert triage, incident report, attack timeline, and security recommendations.",
        link: "./projects/HOME-LAB/part4.html",
        done: true,
      },
    ],
  },
  {
    title: "MITRE ATT&CK Detection Lab — Simulating & Detecting Real-World Attack Techniques with Wazuh",
    desc: "Simulated 8 MITRE ATT&CK techniques against a live Debian victim using Kali Linux, then evaluated Wazuh's detection capability out of the box. Documented a complete attack chain from recon to exfiltration — and found that only 1 out of 8 techniques triggered a meaningful alert.",
    tags: ["Wazuh", "SIEM", "Kali Linux", "Brute Force", "Incident Response", "Home Lab"],
    link: "./projects/HOME-LAB/soc-lab-overview.html",
    done: true,
    category: "Home-Lab",
    // subparts are rendered as an expandable list inside this card
    subparts: [
      {
        label: "Overview",
        title: "Home Lab MITRE ATT&CK Overview",
        desc: "Full-cycle attack simulation and detection using Wazuh SIEM in a home lab environment.",
        link: "./projects/Home-Lab-MITRE-ATT&CK/mitre-lab-intro.html",
        done: true,
      },
      {
        label: "Part 1",
        title: "Attack Simulation & Findings",
        desc: "",
        link: "./projects/Home-Lab-MITRE-ATT&CK/mitre-lab-part2.html",
        done: true,
      },
    ],
  },
];

